### ISSUE TITLE
Model repository creation requires entity ID

### ISSUE THREAD

**Issue by Griffinz** [PromisePay/promisepay-php#22]
Found in Promisepay\UserRepository

Creating a new User failed due to User.ID check in UserRepository->validateUser()

New Users don't have IDs.

**Comment by maccca** [comment]
When creating Items and Users, we track the IDs in your system, ones that you pass us. We can configure things so we generate IDs for you, but by default, IDs must be passed to us.

**Comment by Griffinz** [comment]
Oh wow I've never encountered that before!

Cheers, I will supply our own ID
