### ISSUE TITLE
No timeout set for requests

### ISSUE THREAD

**Issue by mkucej** [PromisePay/promisepay-php#42]
There does not seem to be any connection timeout set for \Httpful\Request. It would be nice to have the ability to set connection timeout in PromisePay configuration like this:

``` PHP
PromisePay::Configuration()->timeout(10);
```

At minimum, some finite timeout should be set as default. Thanks!

**Comment by NinoSkopac** [comment]
Thank you for this suggestion. I agree this is important so I'm implementing it right now, and it will be available in 2.4.4.

**Comment by NinoSkopac** [comment]
To avoid BC, I'll set the default timeout value to 60 seconds.
