### ISSUE TITLE
Use mockery instead of live tests

### ISSUE THREAD

**Issue by NinoSkopac** [PromisePay/promisepay-php#55]

**Comment by NinoSkopac** [comment]
Moving this to 3.0 so we can use Guzzle as a unit testing tool:
- https://stackoverflow.com/a/31245151/1325575
- http://docs.guzzlephp.org/en/stable/testing.html
- https://www.sitepoint.com/unit-testing-guzzlephp/
- https://github.com/php-vcr/php-vcr

**Comment by NinoSkopac** [comment]
*Very* happy with https://github.com/php-vcr/php-vcr, and even happier with https://github.com/php-vcr/phpunit-testlistener-vcr, so I'm gonna use that.

Thank you @jeandee for the suggestion.

**Comment by jeandee** [comment]
No worries! I owe it to @psyfear. :relaxed:
