### ISSUE TITLE
Bug: Fetching ID that contains upper-case characters

### ISSUE THREAD

**Issue by pjhartin** [PromisePay/promisepay-php#63]
Upon updating to v2.4 the ability to search for Items or Users that contain any uppercase characters is now broken. 

The cause is due to this commit: https://github.com/PromisePay/promisepay-php/commit/1beffa6f0138d2b32da2e83cb31e193cffd21ff7#diff-dc345e6a9c1276b4ed44a9e2c376fa35

I have left a comment on the particular line at fault: https://github.com/PromisePay/promisepay-php/commit/1beffa6f0138d2b32da2e83cb31e193cffd21ff7##commitcomment-23711665

This happened to break our system, as we supplied our own IDs during the creation of a User and Items, which did contain uppercase letters. I'm not sure what the best resolution for this is, but since the Assembly site does allow you to provider your own IDs, in whatever case format you require, it perhaps isn't best practice to force the IDs to lower-case, which will result in an "Invalid ID" response.

**Comment by NinoSkopac** [comment]
Hello @pjhartin, thanks for reporting this, and I apologize for the inconvenience.

I'll get this fixed right away. The version with the fix will be 2.4.2.
Of course, you can always use the 2.3 branch which doesn't have this bug.

**Comment by pjhartin** [comment]
Thanks @NinoSkopac - I did roll back to 2.3, but then realised our latest branch had brought in your work on callbacks, so we were stuck! All good now. Thanks!

**Comment by NinoSkopac** [comment]
No problem @pjhartin.

The new tag with the fix is out: https://github.com/PromisePay/promisepay-php/tree/2.4.2
