### ISSUE TITLE
Missing Disbursements endpoints

### ISSUE THREAD

**Issue by NinoSkopac** [PromisePay/promisepay-php#70]
As discovered in https://github.com/PromisePay/promisepay-php/issues/66#issuecomment-325577393, the SDK is missing two endpoints:

**Implement endpoints**
- [x] `GET /disbursements/:id/users`
- [x] `GET disbursements/:id/items`

**Tests**
- [x] /users
- [x] /items

**README**
- [ ] Add examples to README (note: there aren't any examples for Disbursements right now)
- [ ] Update TOC (`doctoc README.md`)

**Comment by NinoSkopac** [comment]
@jeandee Hey, I need your opinion on something.

GET /disbursements/d9fa5f7f-17f5-4b49-a61c-25305d63e6d0/users returns this:

```php
array (
  'created_at' => '2015-05-21T15:28:46.039Z',
  'updated_at' => '2016-06-17T03:30:23.412Z',
  'full_name' => 'test sdfdf edited Test',
  'email' => 'd51de457-2aa1-4f6f-8f5d-216739b5e58a@google.com',
  'mobile' => '+514572146852167395583213125551223',
  'phone' => '+1234567889',
  'logo_url' => NULL,
  'color_1' => NULL,
  'color_2' => NULL,
  'first_name' => 'test sdfdf edited',
  'last_name' => 'Test',
  'id' => 'ec9bf096-c505-4bef-87f6-18822b9dbf2c',
  'custom_descriptor' => NULL,
  'location' => 'AUS',
  'verification_state' => 'pending_check',
  'held_state' => false,
  'roles' => 
  array (
    0 => 'customer',
  ),
  'dob' => 'encrypted',
  'government_number' => 'encrypted',
  'drivers_license' => 'encrypted',
  'flags' => 
  array (
  ),
  'related' => 
  array (
    'addresses' => '18f64cad-f0ff-44f1-a941-8a16f9f29caa',
    'companies' => '4256dbee-671b-495a-908e-0df993e8a5cc',
    'payout_account' => '09b5bb3c-c0fd-404d-b373-d675f42d8865',
  ),
  'links' => 
  array (
    'self' => '/disbursements/d9fa5f7f-17f5-4b49-a61c-25305d63e6d0/users',
    'items' => '/users/ec9bf096-c505-4bef-87f6-18822b9dbf2c/items',
    'card_accounts' => '/users/ec9bf096-c505-4bef-87f6-18822b9dbf2c/card_accounts',
    'paypal_accounts' => '/users/ec9bf096-c505-4bef-87f6-18822b9dbf2c/paypal_accounts',
    'bank_accounts' => '/users/ec9bf096-c505-4bef-87f6-18822b9dbf2c/bank_accounts',
    'wallet_accounts' => '/users/ec9bf096-c505-4bef-87f6-18822b9dbf2c/wallet_accounts',
  ),
)
```

As you can see, it returns one user in the array's root level.
My question is since the endpoint uses the word `users`, plural, shouldn't it return a multidimensional array where each user is in its own array?

**Comment by jeandee** [comment]
@NinoSkopac Let me get back to you on this; currently checking with our QAs as to the intended response for this endpoint.

**Comment by jeandee** [comment]
@NinoSkopac Confirmed with our lead tester that the `GET disbursements/:id/users` does return only one user's information.

You're right that the endpoint `users` is misleading. There's not much we can do on this end unless the endpoint changes. 🙁

**Comment by NinoSkopac** [comment]
@jeandee 

Thank you for letting me know.

**Comment by NinoSkopac** [comment]
Do after reference is updated with Disbursements and #55 is completed.
