### ISSUE TITLE
List Item TDS Checks and Show Item Funding Account

### ISSUE THREAD

**Issue by NinoSkopac** [PromisePay/promisepay-php#73]
@jeandee, I noticed there are 2 new endpoints in prelive reference: List Item TDS Checks and Show Item Funding Account.

Also, there's a TDS Checks/Show TDS Check.

When should these be added to the SDK?

**Comment by jeandee** [comment]
@NinoSkopac Not yet at this point for TDS checks. This is for a 3-D Secure feature we're slated to support. But because this support depends heavily on card schemes and payment gateways, it's a little tricky yet.

I'll get back to you on the Show Item Funding Account call.

**Comment by jeandee** [comment]
@NinoSkopac I've also gotten confirmation that **Show Item Funding Account** is limited to some customers; we do not endorse this call in general production.

**Comment by NinoSkopac** [comment]
Alright, thank you, closing this, then.
