### ISSUE TITLE
Error Message: principal.email: already exists

### ISSUE THREAD

**Issue by wilhelmpaulm** [PromisePay/promisepay-php#80]
I'm using the API and created a user for promisepay. how do I delete that user? since I'm getting `Response Code: 422 Error Message: principal.email: already exists principal: is invalid` when I try to create another user with the same email account.

**Comment by calebwise** [comment]
In a production environment, we have a number of obligations to maintain user records, so account owners cannot delete users. Users on create/update need a unique email address.
